version: '3'

services:
  postgres:
    image: postgres:14.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    container_name: store
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
